/** Chaves centralizadas do TanStack Query, evitando strings soltas. */
export const queryKeys = {
  saldo: ['saldo'] as const,
  meusAgendamentos: ['agendamentos', 'meus'] as const,
  historico: ['agendamentos', 'historico'] as const,
  modalidades: ['modalidades'] as const,
  termo: ['termos', 'vigente'] as const,
  planos: ['planos'] as const,
  vagas: (modalidadeId: string, data: string) => ['horarios', 'vagas', modalidadeId, data] as const,
  horarios: ['horarios'] as const,
  relatorioDashboard: ['relatorios', 'dashboard'] as const,
  relatorioFrequencia: ['relatorios', 'frequencia'] as const,
  creditosMeus: ['creditos', 'meus'] as const,
  creditosSaldo: ['creditos', 'saldo'] as const,
  creditosAdmin: (usuarioId?: string) => ['creditos', 'admin', usuarioId ?? 'all'] as const,
  horariosFixosAdmin: (usuarioId?: string) => ['horarios-fixos', 'admin', usuarioId ?? 'all'] as const,
  agendamentosDoHorario: (horarioId: string, data: string) => ['agendamentos', 'horario', horarioId, data] as const,
  agendamentosDoAluno: (usuarioId: string) => ['agendamentos', 'aluno', usuarioId] as const,
  financeiroMeu: ['financeiro', 'meu'] as const,
  financeiroResumo: ['financeiro', 'resumo'] as const,
  financeiroAluno: (usuarioId?: string) => ['financeiro', 'aluno', usuarioId ?? 'all'] as const,
  treinosMeus: ['treinos', 'meus'] as const,
  treinosAluno: (alunoId?: string) => ['treinos', 'aluno', alunoId ?? 'all'] as const,
  treinoDiaMeu: ['treinos', 'dia', 'meu'] as const,
  treinoDia: (data?: string) => ['treinos', 'dia', data ?? ''] as const,
  cargasMinhas: ['cargas', 'meus'] as const,
  cargasAluno: (alunoId?: string) => ['cargas', 'aluno', alunoId ?? 'all'] as const,
  anamneseMinha: ['anamnese', 'me'] as const,
  anamneseAluno: (alunoId?: string) => ['anamnese', 'aluno', alunoId ?? 'all'] as const,
};
